#!/usr/bin/env php

<?php

use Pnl\Application;

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$classLoader = require 'vendor/autoload.php';

$app = new Application($classLoader);
$app->run();
