services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pnl\App\Command\:
        resource: '../src/App/Command'

    Pnl\Console\:
        resource: '../src/Console'
        exclude:
            - '../src/Console/Input'

    Pnl\Service\:
        resource: '../src/Service'
